name: 02 - Workflow Events
on:
    workflow_dispatch
    schedule:
        - cron: "*/5 * * * *" # Runs every 5 minutes
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: |
               echo "Event name: ${{ github.event_name }}" 
              