name: 07 - Using Expressions
on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
run-name: "07 - Using Expressions | DEBUG - ${{inputs.debug && 'ON' || 'OFF'}}"
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "[debug] Print start-up data"
        if: ${{inputs.debug}} == true
        run: |
          echo "Triggered by: ${{github.event_name}}"
          echo "Branch: ${{github.ref}}"
          echo "Commit SHA: ${{github.sha}}"
          echo "Runner OS: ${{runner.OS}}"
      - name: "[debug] Print when triggered from main"
        if: ${{inputs.debug}} == true && ${{github.event.workflow}} == main
        run: |
          echo "I was triggered from main"
      - name: "Normal Greeting"
        run: |
          echo "Hello, World"
