name: 09 -Using Functions
on:
    pull_request:
    workflow_dispatch:
jobs:
    echo1:
        runs-on: ubuntu-latest
        steps:
            - name: Print PR title
              run: "PR Title: ${{github.event.pull_request.title}}"
            - name: Print PR labels
              run: |
                cat << EOF
                "${{toJson(github.event.pull_request.labels)}}"
                EOF
            - name: Bug Step
              if: ${{failure() && (!cancelled() && contains(github.event.pull_request.title, 'fix'))}}
              run: I am a bug fix
            - name: Sleep for 20 seconds
              run: sleep 20
            - name: Failing Step
              run: exit 1
            - name: I will be skipped
              if: ${{success()}}
              run: "I will print if previous steps succeed" 
            - name: I will execute
              if: ${{failure()}}
              run: I will print if any previous setp fails
            - name: I will execute
              if: ${{ !cancelled()}}
              run: I will always pring, except when the workflow is cancelled
            - name: I will execute when cancelled
              if: ${{ cancelled() }}
              run: I will only execute when the workflow is cancelled
