name: 09 -Using Functions
on:
    push:
    pull_request:
    workflow_dispatch:
jobs:
    echo1:
        runs-on: ubuntu-latest
        steps:
            - name: Failing Step
              run: exit 1
            - name: I will be skipped
              if: ${{success()}}
              run: "I will print if previous steps succeed" 
