name: 12 - Working with Outputs
on:
    workflow_dispatch:
        inputs:
            build-stats:
                type: choice
                options:
                  - success
                  - failure
                default: success
jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            build-status: ${{steps.build.outputs.status}}
            output1: ${{steps.build.outputs.output1}}
            output2: value2

        steps:
            -  name: Print GITHUB_OUTPUT path
               run: |
                    echo $GITHUB_OUTPUT
            - name: Build
              id: build
              run: |
                echo status=${{inputs.build-stats}} >> $GITHUB_OUTPUT
                echo output1=${{inputs.build-stats}} >> $GITHUB_OUTPUT
                echo Before intentional overwrite
                cat $GITHUB_OUTPUT
                echo "mistake=true" > $GITHUB_OUTPUT
                echo After intentional overwrite
                cat $GITHUB_OUTPUT
    deploy:
        runs-on: ubuntu-latest
        needs: build
        if: needs.build.outputs.build-status == 'success'
        steps:
            - name: Deploy
              run: |
                echo Deploying
