name: 15 - Working with Matrices
on:
    workflow_dispatch:

jobs:
    backwards-compatability:
        runs-on: ${{matrix.os}}
        name: ${{matrix.os}}-${{matrix.node}}
        strategy:
            fail-fast: true
            matrix:
                node: [18.x, 20.x, 21.x]
                os:
                    - ubuntu-latest
                    - windows-latest
                include:
                    - os: ubuntu-latest
                      node-version: 16.x
                    - os: ubunutu-latest
                      tag: experimental
                      node-version: 21.x

        steps:
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                node-version: ${{matrix.node-version}}
            - name: Fail if experimental
              if: ${{matrix.tag == 'experimental'}}
              run: exit 1
            - name: Perform some tests
              run: |
                sleep 10
                echo "Running tests on OS ${{matrix.os}} and NodeJS ${{matrix.node-version}}"
            