name: 16 - Working with Environments
on:
    workflow_dispatch:
        #inputs:
            # target-env:
            #     type: environment
            #     description: "Select the target environment"
            #     default: "staging"
#run-name: "16 - Working with Environments | env: ${{inputs.target-env}}"
jobs:
    depploying-staging:
        runs-on: ubuntu-latest
        environment: "staging"
        env:
            my-env-var: ${{vars.MY_ENV_VALUE || 'default-value'}}
        steps:
            - name: Echo vars
              run: |
                echo "Deploying to staging environment"
    e2e-tests:
        runs-on: ubuntu-latest
        needs: depploying-staging
        steps:
            - name: Running E2E tests
              run: |
                echo "Running E2E"
    deploy-prod-frontend:
        runs-on: ubuntu-latest
        needs: e2e-tests
        environment: "prod"
        env:
            my-env-value: ${{vars.MY_ENV_VALUE || 'default value'}}
        steps:
            - name: Echo vars
              run: echo "Deploying to production frontend environment"
    deploy-prod-backend-1:
        runs-on: ubuntu-latest
        needs: e2e-tests
        environment: "prod"
        env:
            my-env-value: ${{vars.MY_ENV_VALUE || 'default value'}}
        steps:
            - name: Echo vars
              run: echo "Deploying to production backend-1 environment"
    deploy-prod-backend-2:
        runs-on: ubuntu-latest
        needs: e2e-tests
        environment: "prod"
        env:
            my-env-value: ${{vars.MY_ENV_VALUE || 'default value'}}
        steps:
            - name: Echo vars
              run: echo "Deploying to production backend-2 environment"