name: 16 - Working with Environments
on:
    workflow_dispatch:
        #inputs:
            # target-env:
            #     type: environment
            #     description: "Select the target environment"
            #     default: "staging"
#run-name: "16 - Working with Environments | env: ${{inputs.target-env}}"
jobs:
    depploying-staging:
        runs-on: ubuntu-latest
        environment: "staging"
        env:
            my-env-var: ${{vars.MY_ENV_VAR || 'default-value'}}
        steps:
            - name: Echo vars
              run: |
                echo "Deploying to staging environment"
    e2e-tests:
        runs-on: ubuntu-latest
        needs: depploying-staging
        steps:
            - name: Running E2E tests
              run: |
                echo "Running E2E"